// flow-typed signature: 4905c86a143c2963b197d4150a13c6b8
// flow-typed version: <<STUB>>/loadash_v^1.0.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'loadash'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'loadash' {
  declare module.exports: any;
}
